# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Get 360Giving Data
email: support@threesixtygiving.org
main_website_url: http://threesixtygiving.org
main_website: 360Giving Website
description: > # this means to ignore newlines until "baseurl:"
  Documentation for developers about how to get the endpoint URLs
  for all known 360Giving data.
baseurl: "/getdata" # the subpath of your site, e.g. /blog
url: "http://threesixtygiving.github.io" # the base hostname & protocol for your site
twitter_username: 360Giving
github_username: ThreeSixtyGiving

# Build settings
markdown: kramdown
